### ISSUE TITLE
2019 Roadmap

### ISSUE THREAD

**Issue by daybrush** [daybrush/scenejs#43]
## Features
* [ ] Add Web Timeline Editor #38 
   - [x] Shape https://github.com/daybrush/shape-svg
   - [x] Dragger https://github.com/daybrush/drag
   - [x] Selector https://github.com/daybrush/moveable
   - [x] Keyboard Controller https://github.com/daybrush/keycon
   - [ ] Timeline Editor https://github.com/daybrush/scenejs-timeline
* [ ] Add Google Extension for Timeline Editor #39 
   - https://github.com/daybrush/scenejs-timeline
* [ ] Add Render(Encoding) App
   - https://github.com/daybrush/scenejs-render
* [ ] Add burst effect
   - https://github.com/daybrush/scenejs-effects
* [ ] Add After Effect Plugin #37 
* [ ] Add JQuery Plugin
* [ ] Make a variety of animations
   - https://codepen.io/collection/DLWxrd/
