### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by daybrush** [daybrush/scenejs#80]
# 2.0 RoadMap

* [x] Update react-scenejs
* [x] Update vue-scenejs
* [x] Add svelte-scenejs
* [x] Add vue3-scenejs
* [ ] Add demo for frameworks
* [ ] Add Motion Tracker
* [ ] Merge repositories (effetcs, renderer, media, iframe)

## changed
* get, set method => getter, settter properties

## deprecated
* ngx-scenejs
* preact-scenejs
